### ISSUE TITLE
Abstract snapshot storage

### ISSUE THREAD

**Issue by tisonkun** [korandoru/zeronos#9]

**Comment by tisonkun** [comment]
Possibly we can store everything in memory at the moment. But still we should do the abstractions and data model.

**Comment by shy-share** [comment]
> Possibly we can store everything in memory at the moment. But still we should do the abstractions and data model.

The data is stored in memory, isn't it stored on disk?

**Comment by tisonkun** [comment]
@shy-share you can regard the in-memory solution as a simple / for testing one, and if we want to provide a consistent key-value store, sooner or later we must investigate storing data on disk. I'm unfamiliar with this domain yet, though.

**Comment by shy-share** [comment]
> @shy-share you can regard the in-memory solution as a simple / for testing one, and if we want to provide a consistent key-value store, sooner or later we must investigate storing data on disk. I'm unfamiliar with this domain yet, though.
> 
> So here we have two aspects to work on:
> 
> 1. Abstract data model.
> 2. Store the data model just in memory or also on the disk.

ok i want to get involved but i don't know exactly what to do, can you give some specific advice

**Comment by tisonkun** [comment]
@shy-share thanks for your interest! This is a side project and I'm still learning the storage part.

A more determinate task in the RoadMap is #8. You can check out [RMap.proto](https://github.com/apache/ratis/blob/323bd1017afdbe03f70cccb172412e6fab221797/ratis-proto/src/main/proto/RMap.proto) definitions, try to support more command and data model in [our simple proto](https://github.com/korandoru/dryad/blob/03ed927aa6d5bd3ac2b04823a45d4d8470563b3c/dryad-core/src/main/proto/Dryad.proto).

Also, the current `dryad-client` is a handy example script. It may be extended to more encapsulated interfaces like [etcd clients](https://github.com/etcdv3/etcd-client/blob/e6c5359af5821f2d712529afb71b0de98639d99a/examples/kv.rs).

These are rough thoughts in my mind now. If you're interested in these topics, feel free to comment in #8 or create issues correspondingly.

If you're interested in the data model and storage part, I'd like to learn from how ZooKeeper and etcd store their data model. I know that ZooKeeper implements its `DataTree` and stores data barely on files with jute serialized, but implementing as is once more is boring :)

**Comment by shy-share** [comment]
@tisonkun ok，iI learned about proto and ratis in the past two days. I found that I have a lot to learn, so take it slow
